### ISSUE TITLE
Orientation diagram or example when connected to talos II

### ISSUE THREAD

**Issue by tlaurion** [3mdeb/talos-tpm-module#2]
Hello there!

The full 20 pins are open as opposed to 19 on the board connector as defined under https://github.com/3mdeb/openpower-coreboot-docs/blob/main/devnotes/tpm_over_lpc.md#talos-ii-tpm-connector

Also, the readme doesn't document what the jumper is for.

It would be interesting that next modules either block the same unavailable pin on connector and/or a picture of the module connected on the motherboard.

**Comment by miczyg1** [comment]
@sulewskiprzemyslaw could you make some photos of the module being connected? Would be great t have them in the [README](https://github.com/3mdeb/talos-tpm-module/blob/main/README.md)

> Also, the readme doesn't document what the jumper us for.

@tlaurion The jumper on the TPM module is for physical presence assertion.

@sulewskiprzemyslaw if you will be at adding photos, could you also add info about the jumper please?

**Comment by tlaurion** [comment]
> @tlaurion The jumper on the TPM module is for physical presence assertion

@miczyg1 then jumper would be nice if provided as well in the package, with a link on product page linking to documentation if not provided with package.


@sulewskiprzemyslaw: Waiting for update, not wanting to short anything putting it in wrong orientation.

Thanks!

**Comment by tlaurion** [comment]
Orientation pictures were posted at https://github.com/Dasharo/dasharo-issues/issues/192#issuecomment-1296906953

**Comment by tlaurion** [comment]
Unfortunately, the platorm doesn't boot when the module is connected (without jumper).
Edit: seemed to have been a glitch.

**Comment by tlaurion** [comment]
The first picture at https://github.com/Dasharo/dasharo-issues/issues/192#issuecomment-1296906953 shows first revision of the TPM module connected to Talos motherboard.

It also shows that rev 1.1 is reversed (top is down, down is up) as compared to rev 1.0 (original)

**Comment by PrzemyslawBanasiak13** [comment]
@tlaurion currently I'm working on those issues. New documentation dedicated to TPM on Talos II will be added and it will contain:

- How/where to purchase the TPM module.
- Info about the module (e.g. about the pinout marked as `U2` on the TPM module)
- Where’s the TPM slot on the device.
- How to mount the TPM (with graphics explanations).
- How to confirm that the module works.

**Comment by tlaurion** [comment]
Hopefully I didn't short anything. Functional testing bug report opened at https://github.com/Dasharo/dasharo-issues/issues/272

**Comment by tlaurion** [comment]
Well, https://github.com/Dasharo/dasharo-issues/issues/272#issuecomment-1335113733 seem to confirm that my module was shorted and is now dead. 

@PrzemyslawBanasiak13 : I would suggest to 3mdeb to make sure PIN 2 is blocked so that misorientation of the board, on rev 1.0/rev 1.1 of the board is not causing similar issues in the future.

**Comment by tlaurion** [comment]
@PrzemyslawBanasiak13 Going to attempt connection of TPM module, trying to find updated doc (@miczyg1 showed on his phone at FOSDEM).

URL of doc is at https://docs.dasharo.com/variants/talos_2/tpm-support/

I guess this can be closed. My issue is under https://github.com/Dasharo/dasharo-issues/issues/272
